name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  common:
    uses: openconfig/common-ci/.github/workflows/basic_go.yml@f00fb472a24f50b2af337466a68e7ca1e5cae78c
    with:
      skip-govet: true
