name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  common:
    uses: openconfig/common-ci/.github/workflows/basic_go.yml@739aa8d155070be7c107c07234dc9d91a4aa061b
    with:
      skip-govet: true
